CustomDefaultValues = { aux1 = 0 }

Mixes = [
	{ InputChannelName = "throttle", OutputChannelName = "throttle" },
	{ InputChannelName = "aileron", OutputChannelName = "aileronL", Expo = 0.6 },
	{ InputChannelName = "aileron", OutputChannelName = "aileronR", Weight = -1, Expo = 0.6 },
	{ InputChannelName = "elevator", OutputChannelName = "elevator", Expo = 0.6 },
	{ InputChannelName = "rudder", OutputChannelName = "rudder", Expo = 0.6 },

	{ InputChannelName = "aux1", OutputChannelName = "aileronL", Expo = 0, Weight = 0.5 },
	{ InputChannelName = "aux1", OutputChannelName = "aileronR", Expo = 0, Weight = 0.5 },
]
