PitchRateDegrees = -360.0
RollRateDegrees = -360.0
YawRateDegrees = -360.0

[PitchTuning]
P = 0.45
# I = 0.8
I = 0
D = 0.3

[RollTuning]
P = 0.45
# I = 0.8
I = 0
D = 0.3

[YawTuning]
P = -1
I = 0
D = 0