name = "Badgerfield Flying Club"
author = "ThatCoolCoder"
version = "0.1.0"
date_created = 2023-03-10
date_updated = 2023-06-18
description = """
A rather small RC club located in the fictional area of Badgerfield. It is surrounded by tall pine trees on all sides, requiring steep approaches.
"""

[location]
world_location = "Maine, USA"
elevation = 50
spawn_positions = [
    { name = "Runway West", aircraft_at = "Positions/RunwayWest", camera_at = "Positions/BehindFenceWest" },
    { name = "Runway East", aircraft_at = "Positions/RunwayEast", camera_at = "Positions/BehindFenceEast" },
    { name = "Shelter", aircraft_at = "Positions/InFrontOfShelter", camera_at = "Positions/UnderShelter" },
]