name = "Ace's Track"
author = "ThatCoolCoder"
version = "0.1.0"
date_created = 2023-06-17
date_updated = 2023-06-17
description = """
An FPV racing track.
"""

[location]
world_location = "Suburban US"
elevation = 0