name = "Large Oval"
author = "ThatCoolCoder"
version = "0.1.0"
date_created = 2023-02-05
date_updated = 2023-04-24
description = """
A large oval based on one near my house.
"""

[location]
world_location = "Suburban US"
elevation = 0