Mixes = [
	{ InputChannelName = "throttle", OutputChannelName = "throttle", Weight = 1.0, Expo = 0.0 },
    
	{ InputChannelName = "elevator", OutputChannelName = "leftElevon", Weight = 1.0, Expo = 0.3, Offset = 0.15 },
	{ InputChannelName = "aileron", OutputChannelName = "leftElevon", Weight = 0.75, Expo = 0.3 },

	{ InputChannelName = "elevator", OutputChannelName = "rightElevon", Weight = 1.0, Expo = 0.3, Offset = 0.15 },
	{ InputChannelName = "aileron", OutputChannelName = "rightElevon", Weight = -0.75, Expo = 0.3 },
]
