name = "Plain Location"
author = "ThatCoolCoder"
version = "0.1.0"
date_created = 2023-01-29
date_updated = 2023-02-25
description = """
A very plain and simple location designed for testing
"""

[location]
world_location = "Abstract place"
elevation = 0
spawn_positions = [
    { name = "Middle", aircraft_at = "StartPosition", camera_at = "CameraPosition" },
]