Mixes = [
	{ InputChannelName = "throttle", OutputChannelName = "throttle" },
	{ InputChannelName = "aileron", OutputChannelName = "rightAileron", Expo = 0.3, Weight = -1 },
	{ InputChannelName = "aileron", OutputChannelName = "leftAileron", Expo = 0.3},
	{ InputChannelName = "elevator", OutputChannelName = "elevator", Expo = 0.3 },
	{ InputChannelName = "rudder", OutputChannelName = "rudder", Expo = 0.3 },

	{ InputChannelName = "aux1", OutputChannelName = "leftAileron", Weight = 0.35, Offset = 1, SpeedUp = 0.5, SpeedDown = 0.5 },
	{ InputChannelName = "aux1", OutputChannelName = "rightAileron", Weight = 0.35,  Offset = 1, SpeedUp = 0.5, SpeedDown = 0.5 },
]
