Mixes = [
	{ InputChannelName = "throttle", OutputChannelName = "throttle", Weight = 1.0, Expo = 0.0 },
	{ InputChannelName = "aileron", OutputChannelName = "rightAileron", Weight = -1.0, Expo = 0.3 },
	{ InputChannelName = "aileron", OutputChannelName = "leftAileron", Weight = 1.0, Expo = 0.3 },
	{ InputChannelName = "elevator", OutputChannelName = "elevator", Weight = 1.0, Expo = 0.3 },
	{ InputChannelName = "rudder", OutputChannelName = "rudder", Weight = 1.0, Expo = 0.3 },

	{ InputChannelName = "flaps", OutputChannelName = "leftAileron", Weight = 0.35, Expo = 0.0, Offset = 1 },
	{ InputChannelName = "flaps", OutputChannelName = "rightAileron", Weight = 0.35, Expo = 0.0, Offset = 1 },
]
