name = "Mini 3D"
author = "ThatCoolCoder"
version = "0.1.0"
date_updated = 2023-03-14
description = """
A small sub-250 monoplane hopefully capable of performing 3d aerobatics.

It is a model of a craft that the author scratch-built, however the real life model did not actually fly very well.
"""

[aircraft]
wingspan = 0.5
length = 0.5
weight = 0.18
power_type = 0
channels = 4

[aircraft.launcher]
speed = 5
height = 1.5
angle = 30